name: Force Update Build Action
description:
  This action increments force update build count, based on the Carepatron Main
  App version.json file, if associated pull request is a force update
author: Carepatron

branding:
  icon: git-pull-request
  color: blue

inputs:
  commit_sha:
    description: The commit SHA from the push event
    required: true
  github_token:
    description: Github Token
    required: true
  owner:
    description: The owner of the repository
    required: true
  repo:
    description: The name of the repository
    required: true
  label:
    description: The label to filter pull requests by
    required: false
  skip_merged_pr_check:
    description:
      Skip checking if pull requests are merged. Default behavior is to filter
      out non-merged pull requests. Set to 'true' to process all pull requests
      regardless of merge status.
    required: false
    default: 'false'

outputs:
  force_update_build_count:
    description: The updated force update build count

runs:
  using: node20
  main: dist/index.js
