name: Force Update Build Action
description:
  This action increments the "force update build count" repository variable if
  the pull requests associated with the commit have a specific label.
author: Carepatron

branding:
  icon: git-pull-request
  color: blue

inputs:
  commit_sha:
    description: The commit SHA from the push event
    required: true
  personal_access_token:
    description: Personal access token for API access
    required: true
  owner:
    description: The owner of the repository
    required: true
  repo:
    description: The name of the repository
    required: true
  label:
    description: The label to filter pull requests by
    required: false
    default: ''
  force_update_build_count_name:
    description: The name of the force update build count repository variable
    required: false
    default: 'FORCE_UPDATE_BUILD_COUNT'

outputs:
  pull_requests:
    description: JSON array of pull requests associated with the commit
  size:
    description: The number of pull requests associated with the commit

runs:
  using: node20
  main: dist/index.js
